name: build-apk
on: workflow_dispatch

jobs:
  build-apk:
    name: build-android
    runs-on: ubuntu-18.04

    steps:

      - name: "get code"
        uses: actions/checkout@v2

      - name: "install python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.9'
          architecture: x64

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: android-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            android-pip-

      - name: "update the machine"
        run: sudo apt-get -y update

      - name: "install python packages"
        run: python3 -m pip install buildozer cython && python3 -m pip install -r requirements.txt

      - name: "install dependencies"
        run: |
          sudo apt install -y zip unzip openjdk-8-jdk && |
          sudo apt-get update && |
          sudo apt-get install build-essential && |
          sudo apt-get install libstdc++6 && |
          sudo apt-get install aidl && |
          sudo apt install -y autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev

      - name: "set path"
        run: cd src && export PATH=$PATH:~/.locl/bin/

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: "compile"
        run: cd src && buildozer -v android debug && ls

      - name: "upload"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.TARGET }}
          path: src/bin/*

